apiVersion: v1
kind: Service
metadata:
  labels:
    component: api
  name: api-service
  namespace: crawler-apps
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: taskQueue
    component: api
