apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-api
  namespace: crawler-apps
  labels:
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskQueue
      component: api
  template:
    metadata:
      labels:
        app: taskQueue
        component: api
    spec:
      containers:
        - name: api
          image: bhonebhone/fb-api:v86
          env:
            - name: FBS_DATABASE_POSTGRESQL_SERVICE_HOST
              value: postgresql://fbs:yah7WUy1Oi8G@192.168.11.202:5432/fbs
            - name: FBS_DATABASE_POSTGRESQL_SLAVE_SERVICE_HOST
              value: postgresql://fbs:yah7WUy1Oi8G@192.168.11.202:5432/fbs
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "150Mi"
              cpu: "50m"
            limits:
              memory: "300Mi"
              cpu: "100m"
      #volumes:
        #- name: screenshots-volume
          #persistentVolumeClaim:
            #claimName: screenshot-pvc